### ISSUE TITLE
asserts

### ISSUE THREAD

**Issue by susanlovaglio** [learn-co-curriculum/swift-dictionaryFun-lab#2]
i think the assert for replacing flavor is wrong. mark exists in the dictionary so maybe it should be flavor changed with the exclamation mark?

`flavorChanged = replaceFlavor("Cookies 'N' Cream", forPerson: "Mark")
assert(flavorChanged, "\(flavorChanged)")`

**Comment by JimCampagno** [comment]
You are correct. I'm actually almost done with completely re-writing this entire lab for Xcode which includes tests.

@susanlovaglio
